# (PART\*) Final considerations {-}

# Summary

R is a programming language and environment that provides a variety of statistical and graphical techniques. We teach and use R because it is **open-sourced**, **compatible** with most operating systems, and because it is used by a **wide and growing community of scientists**. This introduction to R workshop presented the *IDE RStudio*, presented some **basic operation** you can do with R, introduced the concepts of *objects*, *fonctions* and *packages*, and provided some useful ways and resources to **find help** with your analyses in R.

In the **next workshop**, the objectives will be to get familiarize with **R projects** and structuring your code into **scripts**, **manipulating data** in R, and to introduce **packages** specifically used to manipulate `dataframes`.

# Additional resources

## Cheat Sheets

<https://www.rstudio.com/resources/cheatsheets/>

These cheat sheets are also directly available in RStudio (Help -\>
Cheat Sheets)

------------------------------------------------------------------------

## Books

-   [R for Dummies](http://sgpwe.izt.uam.mx/files/users/uami/gma/R_for_dummies.pdf) (*available online*)
-   [A Handbook of Statistical Analyses using R](https://www.routledge.com/A-Handbook-of-Statistical-Analyses-using-R/Hothorn-Everitt/p/book/9781482204582)
-   [R in Action](https://www.manning.com/books/r-in-action) (*available online*)
-   [Introductory Statistics in R](https://www.springer.com/gp/book/9780387790534)
-   [A Beginner's Guide to R](https://link-springer-com.proxy3.library.mcgill.ca/book/10.1007/978-0-387-93837-0)
-   [The R Book](https://www.wiley.com/en-us/The+R+Book%2C+2nd+Edition-p-9780470973929)

------------------------------------------------------------------------

## Useful links

- [Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.html)
- [R reference card](https://cran.r-project.org/doc/contrib/Baggott-refcard-v2.pdf)
- [Quick-R](https://www.statmethods.net)
- [Cookbook for R](http://cookbook-r.com)
- [R for Data Science](http://r4ds.had.co.nz/index.html)
