# (PART\*) Analyses multivariées en `R` {-}

# Objectifs d'apprentissage

**Résumé :** Durant cet atelier, vous apprendrez ce qu'est le logiciel
d'analyse statistique R et vous découvrirai plusieurs raisons pourquoi
vous devriez l'utiliser. Vous ferez vos premiers pas dans ce logiciel:
Vous verrez comment R peut être utilisé comme une calculatrice, vous
apprendrez ce qu'est un « objet » dans R, et vous utiliserez des
fonctions simples. De plus, vous apprendrez comment télécharger de
nouvelles fonctions et comment trouver des ressources d'aide pour
utiliser R. Si tout ceci vous semble étrange, ne vous inquiétez pas! À
la fin de cet atelier, vous comprendrez tous ces concepts:

1.  Comprendre ce que sont R et RStudio
2.  Utiliser R comme une calculatrice
3.  Manipuler les objets dans R
4.  Installer et utiliser les packages R
5.  Obtenir de l'aide

# Préparez-vous pour cet atelier

```{r eval=FALSE, echo=FALSE, purl=TRUE}
##### Avis ###
###                                                                             #
### Ceci est un script généré automatiquement basé sur les morceaux de code du  #
### livre pour cet atelier.                                                     #
###                                                                             #
### Il est minimalement annoté pour permettre aux participants de fournir leurs #
### commentaires : une pratique que nous encourageons vivement.                 #
###                                                                             #
### Notez que les solutions aux défis sont également incluses dans ce script.   #
### Lorsque vous résolvez les défis par vous-méme, essayez de ne pas parcourir  #
### le code et de regarder les solutions.                                       #
###                                                                             # 
### Bon codage !                                                               #

```

Tout le matériel de l'atelier se trouve sur [github.com/QCBSRworkshops/workshop01](https://github.com/QCBSRworkshops/workshop01). Cela inclut un [script R](https://r.qcbs.ca/workshop01/book-fr/workshop01-script-fr.R) qui rassemble tous les morceaux de code présentés dans ce livre.

Avant de débuter cet atelier, vous devez installer les logiciels R et R
Studio sur votre ordinateur personnel. Pour obtenir le logiciel R,
rendez-vous au <http://www.r-project.org/> et cliquez sur « Download ».
Vous devez sélectionner un site miroir (préférablement un situé près de
vous) et choisir votre plateforme (OS X, Windows ou Linux). Téléchargez
le fichier et lancez-le afin de compléter l'installation. Vous pouvez
garder les paramètres d'installation par défaut.

Pour installer R Studio, rendez-vous au <http://www.rstudio.com/> et
sélectionnez R Studio à partir de l'onglet « Products tab ». Cliquez sur
la version en source libre (*i.e.* open source) du « R Studio Desktop »
et sélectionnez votre plateforme pour le télécharger. Lancez le fichier
d'installation afin de compléter l'installation. Encore une fois, vous
pouvez garder les paramètres d'installation par défaut.

Vous pouvez aussi télécharger le script R pour cet atelier:

-   [script R](https://r.qcbs.ca/workshop01/book-fr/workshop01-script-fr.R)
